apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: default
  labels:
    app: redis-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-dev
  template:
    metadata:
      labels:
        app: redis-dev
    spec:
      containers:
      - image: redis:6.0.14
        imagePullPolicy: IfNotPresent      
        name: redis
        ports:
        - containerPort: 6379
          protocol: TCP
        securityContext: # 如果不指定运行用户可能报错： Error: container has runAsNonRoot and image will run as root 
          runAsUser: 1000
          runAsNonRoot: true        
---          
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: default
spec:
  selector:
    app: redis-dev
  type: ClusterIP
  ports:
    - name: tcp-port
      port: 6379
      targetPort: 6379
      protocol: TCP      