apiVersion: v1
kind: ServiceAccount
metadata:
  name: xc
  namespace: hello

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xc-role
  # "namespace" 被忽略，因为 ClusterRoles 不受名字空间限制
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/metrics", "services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: xc-role-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: xc-role
subjects:
- kind: ServiceAccount
  name: xc
  namespace: hello